#!/bin/bash

CHECKPATCH="/usr/local/bin/checkpatch.pl"

if [[ ! -e ${CHECKPATCH} ]]; then
	CHECKPATCH=${HOME}/bin/checkpatch.pl
fi

if [ ! -x "${CHECKPATCH}" ]; then
	echo "cannot execute '${CHECKPATCH}'"
	exit 1
fi

CHECKPATCH_FLAGS+=" --no-tree"
CHECKPATCH_FLAGS+=" --ignore GERRIT_CHANGE_ID"
CHECKPATCH_FLAGS+=" --ignore COMPLEX_MACRO"
CHECKPATCH_FLAGS+=" --ignore TRAILING_SEMICOLON"
#CHECKPATCH_FLAGS+=" --ignore LONG_LINE"
#CHECKPATCH_FLAGS+=" --ignore LONG_LINE_STRING"
#CHECKPATCH_FLAGS+=" --ignore LONG_LINE_COMMENT"
#CHECKPATCH_FLAGS+=" --ignore SYMBOLIC_PERMS"
#CHECKPATCH_FLAGS+=" --ignore NEW_TYPEDEFS"
#CHECKPATCH_FLAGS+=" --ignore SPLIT_STRING"
#CHECKPATCH_FLAGS+=" --ignore USE_FUNC"
#CHECKPATCH_FLAGS+=" --ignore COMMIT_LOG_LONG_LINE"
CHECKPATCH_FLAGS+=" --ignore FILE_PATH_CHANGES"
CHECKPATCH_FLAGS+=" --ignore MISSING_SIGN_OFF"
#CHECKPATCH_FLAGS+=" --ignore RETURN_PARENTHESES"
#CHECKPATCH_FLAGS+=" --ignore STATIC_CONST_CHAR_ARRAY"
#CHECKPATCH_FLAGS+=" --ignore ARRAY_SIZE"
#CHECKPATCH_FLAGS+=" --ignore NAKED_SSCANF"
#CHECKPATCH_FLAGS+=" --ignore SSCANF_TO_KSTRTO"
#CHECKPATCH_FLAGS+=" --ignore EXECUTE_PERMISSIONS"
#CHECKPATCH_FLAGS+=" --ignore MULTISTATEMENT_MACRO_USE_DO_WHILE"
#CHECKPATCH_FLAGS+=" --ignore STORAGE_CLASS"
CHECKPATCH_FLAGS+=" --ignore SPDX_LICENSE_TAG"
CHECKPATCH_FLAGS+=" --ignore PRINTK_WITHOUT_KERN_LEVEL"
# checkpatch.pl will ignore the following paths
# readonly CHECKPATCH_IGNORE+=" Makefile"
# readonly CHECKPATCH_EXCLUDE=$(for p in ${CHECKPATCH_IGNORE}; do echo ":(exclude)${p}" ; done)

checkpatch() {
	if [ -n "$2" ];then
	patch=$(git format-patch -1 "$1" -- "$2" -o ${DEFAULT_PATCH_OUT})
	else
	patch=$(git format-patch -1 "$1" -o ${DEFAULT_PATCH_OUT})
	fi

        if [ -n "${patch}" ];then
		echo ""
		echo "-------- Check Commit --------------"
		git show --oneline --no-patch "$1"
		echo "------------------------------------"
		echo ""
		echo ""

		perl ${CHECKPATCH} ${CHECKPATCH_FLAGS}  ${patch}
		echo ""
	else
		echo "Not Patch Generated"
		exit 0
        fi
}

readonly COMMIT="${1:-HEAD}"

DEFAULT_PATCH_OUT='./KAKAZZCR_PATCH'

rm -rf ${DEFAULT_PATCH_OUT}
mkdir -p ${DEFAULT_PATCH_OUT}

checkpatch "${COMMIT}" $2

rm -rf ${DEFAULT_PATCH_OUT}
